// <auto-generated />
using System;
using BlotterSync.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlotterSync.Migrations
{
    [DbContext(typeof(BlotterSyncContext))]
    partial class BlotterSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlotterSync.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostedByOfficerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("BlotterSync.Models.BlotterRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplainantId")
                        .HasColumnType("int");

                    b.Property<int>("DeskOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("RespondentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecordId")
                        .HasName("PK__BlotterR__FBDF78E9C14F26A9");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComplainantId");

                    b.HasIndex("DeskOfficerId");

                    b.HasIndex("RespondentId");

                    b.HasIndex(new[] { "TrackingNumber" }, "UQ__BlotterR__784DB3D9D658DE32")
                        .IsUnique();

                    b.ToTable("BlotterRecords");
                });

            modelBuilder.Entity("BlotterSync.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("int");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B064FE278");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BlotterSync.Models.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CitizenId")
                        .HasName("PK__Citizens__6E49FA0C8F1A3E91");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("BlotterSync.Models.Involvement", b =>
                {
                    b.Property<int>("InvolvementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvolvementId"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Statement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvolvementId")
                        .HasName("PK__Involvem__A7B85E33D5021004");

                    b.HasIndex("CitizenId");

                    b.HasIndex("RecordId");

                    b.ToTable("Involvements");
                });

            modelBuilder.Entity("BlotterSync.Models.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<bool?>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Officer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OfficerId")
                        .HasName("PK__Officers__2E65577A9E7C9A2C");

                    b.HasIndex(new[] { "Username" }, "UQ_Officers_Username")
                        .IsUnique();

                    b.HasIndex(new[] { "BadgeNumber" }, "UQ__Officers__D110FD56D35C9A0C")
                        .IsUnique();

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("BlotterSync.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ResidentId")
                        .HasName("PK__Resident__07FB00DC9C87A8DE");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("BlotterSync.Models.BlotterRecord", b =>
                {
                    b.HasOne("BlotterSync.Models.Category", "Category")
                        .WithMany("BlotterRecords")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__BlotterRe__Categ__3E52440B");

                    b.HasOne("BlotterSync.Models.Resident", "Complainant")
                        .WithMany("BlotterRecordComplainants")
                        .HasForeignKey("ComplainantId")
                        .HasConstraintName("FK__BlotterRe__Compl__4BAC3F29");

                    b.HasOne("BlotterSync.Models.Officer", "DeskOfficer")
                        .WithMany("BlotterRecords")
                        .HasForeignKey("DeskOfficerId")
                        .IsRequired()
                        .HasConstraintName("FK__BlotterRe__DeskO__3F466844");

                    b.HasOne("BlotterSync.Models.Resident", "Respondent")
                        .WithMany("BlotterRecordRespondents")
                        .HasForeignKey("RespondentId")
                        .HasConstraintName("FK__BlotterRe__Respo__4CA06362");

                    b.Navigation("Category");

                    b.Navigation("Complainant");

                    b.Navigation("DeskOfficer");

                    b.Navigation("Respondent");
                });

            modelBuilder.Entity("BlotterSync.Models.Involvement", b =>
                {
                    b.HasOne("BlotterSync.Models.Citizen", "Citizen")
                        .WithMany("Involvements")
                        .HasForeignKey("CitizenId")
                        .IsRequired()
                        .HasConstraintName("FK__Involveme__Citiz__45F365D3");

                    b.HasOne("BlotterSync.Models.BlotterRecord", "Record")
                        .WithMany("Involvements")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK__Involveme__Recor__44FF419A");

                    b.Navigation("Citizen");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("BlotterSync.Models.BlotterRecord", b =>
                {
                    b.Navigation("Involvements");
                });

            modelBuilder.Entity("BlotterSync.Models.Category", b =>
                {
                    b.Navigation("BlotterRecords");
                });

            modelBuilder.Entity("BlotterSync.Models.Citizen", b =>
                {
                    b.Navigation("Involvements");
                });

            modelBuilder.Entity("BlotterSync.Models.Officer", b =>
                {
                    b.Navigation("BlotterRecords");
                });

            modelBuilder.Entity("BlotterSync.Models.Resident", b =>
                {
                    b.Navigation("BlotterRecordComplainants");

                    b.Navigation("BlotterRecordRespondents");
                });
#pragma warning restore 612, 618
        }
    }
}
