@BlotterSync_HostAddress = http://localhost:5180

POST {{BlotterSync_HostAddress}}/api/Auth/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "changeme"
}

###

GET {{BlotterSync_HostAddress}}/api/BlotterRecords/Public
Accept: application/json

###

GET {{BlotterSync_HostAddress}}/api/Announcements/Active
Accept: application/json

###
