-- =============================================================================
-- BlotterSync - Converted PostgreSQL / Supabase Migration Script
-- Converted from Classmate's Microsoft SQL Server (T-SQL) script
-- =============================================================================
-- How to run this in Supabase:
-- 1. Open your Supabase Dashboard (https://supabase.com/dashboard)
-- 2. Click "SQL Editor" in the left navigation sidebar
-- 3. Click "New query"
-- 4. Paste this script and click "Run" (or Ctrl + Enter)
-- =============================================================================

-- =========================================================
-- 1. DATABASE TABLES CREATION (PostgreSQL Compatible)
-- =========================================================

-- 1.1 Officers Table (Administrative Accounts)
CREATE TABLE IF NOT EXISTS "Officers" (
    "OfficerId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BadgeNumber" VARCHAR(50) NOT NULL,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" VARCHAR(100) NOT NULL,
    "Username" VARCHAR(100) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(255) NOT NULL,
    "Role" VARCHAR(50) NOT NULL DEFAULT 'Officer',
    "ActiveStatus" BOOLEAN NOT NULL DEFAULT TRUE
);

-- 1.2 Residents Table (Citizen Complainants / Respondents)
CREATE TABLE IF NOT EXISTS "Residents" (
    "ResidentId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" VARCHAR(100) NOT NULL,
    "ContactNumber" VARCHAR(20) NULL,
    "Address" VARCHAR(255) NOT NULL,
    "Zone" VARCHAR(50) NULL
);

-- 1.3 Categories Table (Incident Classification)
CREATE TABLE IF NOT EXISTS "Categories" (
    "CategoryId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "SeverityLevel" INT NOT NULL
);

-- 1.4 BlotterRecords Table (Central Incident Archive)
-- NOTE: In your ASP.NET Core EF Core backend (BlotterRecord.cs), the primary key 
-- is named "RecordId". Using "RecordId" ensures 100% compatibility with your C# models.
CREATE TABLE IF NOT EXISTS "BlotterRecords" (
    "RecordId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TrackingNumber" VARCHAR(50) NOT NULL UNIQUE,
    "CategoryId" INT NOT NULL,
    "DeskOfficerId" INT NOT NULL,
    "ComplainantId" INT NOT NULL,
    "RespondentId" INT NULL,
    "IncidentDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "ReportedDate" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "Location" VARCHAR(255) NOT NULL,
    "Narrative" TEXT NOT NULL,
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "ResolutionDate" TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT "FK_BlotterRecords_Categories" FOREIGN KEY ("CategoryId") 
        REFERENCES "Categories" ("CategoryId"),
    CONSTRAINT "FK_BlotterRecords_Officers" FOREIGN KEY ("DeskOfficerId") 
        REFERENCES "Officers" ("OfficerId"),
    CONSTRAINT "FK_BlotterRecords_Residents_Complainant" FOREIGN KEY ("ComplainantId") 
        REFERENCES "Residents" ("ResidentId"),
    CONSTRAINT "FK_BlotterRecords_Residents_Respondent" FOREIGN KEY ("RespondentId") 
        REFERENCES "Residents" ("ResidentId")
);

-- 1.5 Announcements Table (Public Kiosk Bulletins)
CREATE TABLE IF NOT EXISTS "Announcements" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Message" TEXT NOT NULL,
    "DatePosted" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PostedByOfficerId" INT NOT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_Announcements_Officers" FOREIGN KEY ("PostedByOfficerId") 
        REFERENCES "Officers" ("OfficerId")
);

-- Create Indexes for foreign key lookup performance
CREATE INDEX IF NOT EXISTS "IX_BlotterRecords_CategoryId" ON "BlotterRecords" ("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_BlotterRecords_DeskOfficerId" ON "BlotterRecords" ("DeskOfficerId");
CREATE INDEX IF NOT EXISTS "IX_BlotterRecords_ComplainantId" ON "BlotterRecords" ("ComplainantId");
CREATE INDEX IF NOT EXISTS "IX_BlotterRecords_RespondentId" ON "BlotterRecords" ("RespondentId");

-- Ensure all columns exist on previously created tables (idempotent migration)
ALTER TABLE "Residents" ADD COLUMN IF NOT EXISTS "Zone" VARCHAR(50);
ALTER TABLE "Residents" ADD COLUMN IF NOT EXISTS "ContactNumber" VARCHAR(20);
ALTER TABLE "Officers" ADD COLUMN IF NOT EXISTS "Role" VARCHAR(50) DEFAULT 'Officer';
ALTER TABLE "Officers" ADD COLUMN IF NOT EXISTS "ActiveStatus" BOOLEAN DEFAULT TRUE;
ALTER TABLE "BlotterRecords" ADD COLUMN IF NOT EXISTS "ReportedDate" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "BlotterRecords" ADD COLUMN IF NOT EXISTS "ResolutionDate" TIMESTAMP WITHOUT TIME ZONE NULL;
ALTER TABLE "BlotterRecords" ADD COLUMN IF NOT EXISTS "ComplainantId" INT;
ALTER TABLE "BlotterRecords" ADD COLUMN IF NOT EXISTS "RespondentId" INT;

-- =========================================================
-- 2. SEED INITIAL DATA
-- =========================================================

-- 2.1 Seed Incident Categories (Safely without duplicates)
-- Reassign and delete any existing duplicate categories
UPDATE "BlotterRecords" SET "CategoryId" = 1 WHERE "CategoryId" = 19;
UPDATE "BlotterRecords" SET "CategoryId" = 2 WHERE "CategoryId" = 18;
UPDATE "BlotterRecords" SET "CategoryId" = 4 WHERE "CategoryId" = 21;
UPDATE "BlotterRecords" SET "CategoryId" = 5 WHERE "CategoryId" = 20;
DELETE FROM "Categories" WHERE "CategoryId" IN (18, 19, 20, 21);

-- Update existing categories to their canonical names
UPDATE "Categories" SET "Name" = 'Theft / Robbery', "SeverityLevel" = 3 WHERE "CategoryId" = 1;
UPDATE "Categories" SET "Name" = 'Physical Injury / Assault', "SeverityLevel" = 4 WHERE "CategoryId" = 2;
UPDATE "Categories" SET "Name" = 'Vandalism / Property Damage', "SeverityLevel" = 2 WHERE "CategoryId" = 4;
UPDATE "Categories" SET "Name" = 'Disturbance of Peace / Noise', "SeverityLevel" = 1 WHERE "CategoryId" = 5;

-- Insert any missing categories
INSERT INTO "Categories" ("Name", "SeverityLevel")
SELECT name, severity
FROM (VALUES
    ('Theft / Robbery', 3),
    ('Physical Injury / Assault', 4),
    ('Vandalism / Property Damage', 2),
    ('Disturbance of Peace / Noise', 1),
    ('Trespassing', 2),
    ('Cyberbullying / Online Threats', 2)
) AS v(name, severity)
WHERE NOT EXISTS (
    SELECT 1 FROM "Categories" WHERE "Name" = v.name
);

-- 2.2 Seed Default Administrative Officer (Password: Admin123)
-- AuthController automatically hashes plaintext passwords to ASP.NET Identity PBKDF2 on first login.
INSERT INTO "Officers" ("BadgeNumber", "FirstName", "LastName", "Username", "PasswordHash", "Role", "ActiveStatus")
SELECT 'MNL-001', 'Admin', 'DeskOfficer', 'admin', 'Admin123', 'Admin', TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM "Officers" WHERE "Username" = 'admin'
);

-- Ensure Zone column exists on Residents if the table was created previously without it
ALTER TABLE "Residents" ADD COLUMN IF NOT EXISTS "Zone" VARCHAR(50);

-- 2.3 Seed Sample Resident Record
INSERT INTO "Residents" ("FirstName", "LastName", "ContactNumber", "Address", "Zone")
SELECT 'Juan', 'Dela Cruz', '09123456789', 'Malanday St.', 'Zone 1'
WHERE NOT EXISTS (
    SELECT 1 FROM "Residents" WHERE "FirstName" = 'Juan' AND "LastName" = 'Dela Cruz'
);

-- 2.4 Seed Initial Public Kiosk Announcement
INSERT INTO "Announcements" ("Message", "DatePosted", "PostedByOfficerId", "IsActive")
SELECT 'Curfew for minors remains strictly enforced from 10:00 PM to 4:00 AM.', CURRENT_TIMESTAMP, 1, TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM "Announcements" WHERE "Message" LIKE 'Curfew for minors%'
);

-- 2.5 Seed Sample Incident Record
INSERT INTO "BlotterRecords" (
    "TrackingNumber", "CategoryId", "DeskOfficerId", "ComplainantId", "RespondentId", 
    "IncidentDate", "Location", "Narrative", "Status"
)
SELECT 
    'BS-20261009-TEST1',
    1,
    1,
    1,
    NULL,
    CURRENT_TIMESTAMP,
    'Zone 1, Barangay Malanday',
    E'WHAT: Unattended bicycle stolen outside convenience store.\r\nWHY: Opportunity theft.\r\nHOW: Cut cable lock with manual bolt cutters.',
    'Pending'
WHERE NOT EXISTS (
    SELECT 1 FROM "BlotterRecords" WHERE "TrackingNumber" = 'BS-20261009-TEST1'
);
